name: CI-CD pipeline

on:
    push:
        branches:
            - main

jobs:
    test-job:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: install dependencies
              run: pip install -r requirements

            - name: run test cases
              run: pytest --cov=calc --cov-report=term

    deploy-job:
        runs-on: ubuntu-latest
        needs: test-job
        steps:
            - name: print message
              run: echo "display job started"
